name: LLVM Windows
on:
  push:
    paths:
      - '.github/workflows/llvm-11.1.0-windows-custom.yml'
  workflow_dispatch:
    inputs:
      BUILD_TYPE:
        description: 'Build Type'
        required: true
        default: 'Debug' 
        type: choice
        options:
        - 'Debug'
        - 'RelWithDebInfo'
        - 'Release' 

env:
  VERSION: 11.1.0
  BUILD_DIR: build
  INSTALL_PATH: ${{github.workspace}}/install/llvm

jobs:
  build_llvm:
    if:  ${{ inputs.BUILD_TYPE }}
    name: Build LLVM on Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Setup Windows
      uses: llvm/actions/setup-windows@main
      with:
        arch: amd64

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Build
      # Use this as our working directory for all subsequent commands
      run: |
        cmake -E make_directory $BUILD_DIR
        cmake -E make_directory $INSTALL_PATH
        cd $BUILD_DIR
        cmake $GITHUB_WORKSPACE/llvm -DCMAKE_BUILD_TYPE=${{inputs.BUILD_TYPE}} -DLLVM_ENABLE_PROJECTS=lld -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH
        cmake --build . --config ${{inputs.BUILD_TYPE}} --target install
        cd $INSTALL_PATH/..
        7z a $GITHUB_WORKSPACE/llvm-${{env.VERSION}}-${{inputs.BUILD_TYPE}}-win-x64.zip *

    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: LLVM ${{env.VERSION}} Windows ${{inputs.BUILD_TYPE}}
        tag_name: v${{env.VERSION}}-${{inputs.BUILD_TYPE}}-win-x64
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: llvm-${{env.VERSION}}-${{inputs.BUILD_TYPE}}-win-x64.zip
        asset_name: llvm-${{env.VERSION}}-${{inputs.BUILD_TYPE}}-win-x64.zip
        asset_content_type: application/gzip
