name: LLVM macOS Release

on:
  push:
    branches:
      - 'fly-llvm-11.1.0'
  
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

env:
  VERSION: 11.1.0
  BUILD_DIR: build
  BUILD_TYPE: Release
  INSTALL_PATH: ${{github.workspace}}/build/install

jobs:
  build_llvm:
    name: Build LLVM on macOS
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Build
      # Use this as our working directory for all subsequent commands
      run: |
        cmake -E make_directory $BUILD_DIR
        cmake -E make_directory $INSTALL_PATH
        cd $BUILD_DIR
        cmake $GITHUB_WORKSPACE/llvm -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH
        cmake --build . --config $BUILD_TYPE --target install
        cd $INSTALL_PATH
        tar -czvf ${{github.workspace}}/llvm-${{env.VERSION}}-x86_64-apple-darwin.tar.gz *

    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: LLVM ${{env.VERSION}} macOS Release
        tag_name: v${{env.VERSION}}-macos-x86_64
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: llvm-${{env.VERSION}}-x86_64-apple-darwin.tar.gz
        asset_name: llvm-${{env.VERSION}}-x86_64-apple-darwin.tar.gz
        asset_content_type: application/gzip
