name: LLVM Linux Release

on:
  push:
    branches:
      - 'fly-llvm-11.1.0'
  
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

env:
  VERSION: 11.1.0
  BUILD_PATH: ${{github.workspace}}/build
  BUILD_TYPE: Release

jobs:
  build_llvm:
    name: Build LLVM on Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Build
      # Use this as our working directory for all subsequent commands
      run: |
        pwd
        cmake -E make_directory $BUILD_PATH
        cd $BUILD_PATH
        cmake $GITHUB_WORKSPACE/llvm -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        cmake --build . --config $BUILD_TYPE --target install
        tar -czvf ${{github.workspace}}/llvm-${{env.VERSION}}-x86_64-linux-gnu.tar.gz *

    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: LLVM ${{env.VERSION}} Linux Release
        tag_name: v${{env.VERSION}}-linux-x86_64
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: llvm-${{env.VERSION}}-x86_64-linux-gnu.tar.gz
        asset_name: llvm-${{env.VERSION}}-x86_64-linux-gnu.tar.gz
        asset_content_type: application/gzip
