name: LLVM Windows Release

on:
  push:
    branches:
      - 'fly-llvm-11.1.0'
  
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

env:
  VERSION: 11.1.0
  BUILD_DIR: build
  BUILD_TYPE: Release

jobs:
  build_llvm:
    name: Build LLVM on Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Setup Windows
      uses: llvm/actions/setup-windows@main
      with:
        arch: amd64

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Build
      # Use this as our working directory for all subsequent commands
      run: |
        cmake -E make_directory $BUILD_DIR
        cd $BUILD_DIR
        cmake $GITHUB_WORKSPACE/llvm -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        cmake --build . --config $BUILD_TYPE
        7z a ${{github.workspace}}/llvm-${{env.version}}-win-x64.zip *

    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: LLVM ${{env.VERSION}} Windows Release
        tag_name: v${{env.VERSION}}-win-x64
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: llvm-${{env.version}}-win-x64.zip
        asset_name: llvm-${{env.version}}-win-x64.zip
        asset_content_type: application/gzip
