name: LLVM Windows Debug

on:
  push:
    branches:
      - 'fly-llvm-11.1.0'
  
# Allows you to run this workflow manually from the Actions
  workflow_dispatch:  

env:
  VERSION: 11.1.0
  BUILD_DIR: build
  BUILD_TYPE: Debug
  INSTALL_PATH: ${{github.workspace}}/build/install

jobs:
  build_llvm:
    name: Build LLVM on Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Setup Windows
      uses: llvm/actions/setup-windows@main
      with:
        arch: amd64

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Build
      # Use this as our working directory for all subsequent commands
      run: |
        cmake -E make_directory $BUILD_DIR
        cmake -E make_directory $INSTALL_PATH
        cd $BUILD_DIR
        cmake $GITHUB_WORKSPACE/llvm -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLLVM_ENABLE_PROJECTS=lld -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH
        cmake --build . --config $BUILD_TYPE --target install
        cd $INSTALL_PATH
        7z a $GITHUB_WORKSPACE/llvm-${{env.VERSION}}-${{BUILD_TYPE}}-win-x64.zip *

    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: LLVM ${{env.VERSION}} Windows ${{BUILD_TYPE}}
        tag_name: v${{env.VERSION}}-${{BUILD_TYPE}}-win-x64
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: llvm-${{env.VERSION}}-${{BUILD_TYPE}}-win-x64.zip
        asset_name: llvm-${{env.VERSION}}-${{BUILD_TYPE}}-win-x64.zip
        asset_content_type: application/gzip
